# Generated by Django 4.1.3 on 2022-11-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_episodio'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='video',
            field=models.URLField(default='your link...'),
        ),
    ]
